name: Environ Me'
description: 'Generate environment specific content by combinding a template file and a properites file'
branding:
  icon: 'sunrise'  
  color: 'yellow'
inputs:
  path:  # id of input
    description: 'wildcard path to template files that will be used to generate output'
    required: true
    default: '*'
  targetEnvironment:  # id of input
    description: 'Environment key used to override configuration in properties object that will be replaced into template file'
    required: false
  branchMapping:
    description: "Key/value array representing branch mapping to environment in form branch1=Evn1,branch2=Env2.."
    required: false

runs:
  using: 'node12'
  main: 'index.js'